"""Apply naming convention

Revision ID: 44694fe8bc38
Revises: 8a48e554f1de
Create Date: 2025-11-23 20:45:26.479796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44694fe8bc38'
down_revision = '8a48e554f1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_name'), type_='unique')

    # ### end Alembic commands ###
